### ISSUE TITLE
data_fixture='random' doesn't work

### ISSUE THREAD

**Issue by qris** [paulocheque/django-dynamic-fixture#31]
The docs say you can do:

```
G(MyModel, data_fixture='random')
```

But this doesn't work:

```
Traceback (most recent call last):
File "/home/installuser/projects/inaspsite/django/website/perireg/tests/accept_reject_application_for_resource_tests.py", line 213, in test_reapprove_updated_registration_form_loads_with_all_fields_changed
    new_inst = new(Institution, data_fixture='random')
File "/home/installuser/projects/inaspsite/django/website/.ve/local/lib/python2.7/site-packages/django_dynamic_fixture/__init__.py", line 79, in new
    return d.new(model, shelve=shelve, persist_dependencies=persist_dependencies, **kwargs)
File "/home/installuser/projects/inaspsite/django/website/.ve/local/lib/python2.7/site-packages/django_dynamic_fixture/ddf.py", line 441, in new
    self.set_data_for_a_field(model_class, instance, field, persist_dependencies=persist_dependencies, **configuration)
File "/home/installuser/projects/inaspsite/django/website/.ve/local/lib/python2.7/site-packages/django_dynamic_fixture/ddf.py", line 348, in set_data_for_a_field
    data = self._process_field_with_default_fixture(field, model_class, persist_dependencies)
File "/home/installuser/projects/inaspsite/django/website/.ve/local/lib/python2.7/site-packages/django_dynamic_fixture/ddf.py", line 335, in _process_field_with_default_fixture
    data = self.data_fixture.generate_data(field)
AttributeError: 'str' object has no attribute 'generate_data'
```

I suspect I should be creating an instance of RandomDataFixture() instead?

**Comment by simenheg** [comment]
This issue is still present in the documentation, under [Overriding global data fixture](http://django-dynamic-fixture.readthedocs.org/en/latest/data_fixtures.html#overriding-global-data-fixture). Doing `G(MyModel, data_fixture='sequential')` is also suggested, which results in the same error.

**Comment by paulocheque** [comment]
Fixed: https://github.com/paulocheque/django-dynamic-fixture/pull/110

Thanks again for the contribution.
