### ISSUE TITLE
Bug using SimpleUploadedFile

### ISSUE THREAD

**Issue by valdergallo** [paulocheque/django-dynamic-fixture#76]
Was implemented one new library in django to create tests files called [SimpleUploadedFile](https://docs.djangoproject.com/en/dev/ref/forms/api/#binding-uploaded-files-to-a-form)

The problem happen when you try send one SimpleUploadedFile to create one file instance. 

```
Traceback (most recent call last):
  File "/vagrant/goal_design/tests/test_views.py", line 24, in test_download_documentation
    is_last_version="true")
  File "/home/vagrant/.virtualenvs/env/local/lib/python2.7/site-packages/django_dynamic_fixture/__init__.py", line 106, in get
    return d.get(model, shelve=shelve, **kwargs)
  File "/home/vagrant/.virtualenvs/env/local/lib/python2.7/site-packages/django_dynamic_fixture/ddf.py", line 528, in get
    instance = self.new(model_class, shelve=shelve, named_shelve=named_shelve, **kwargs)
  File "/home/vagrant/.virtualenvs/env/local/lib/python2.7/site-packages/django_dynamic_fixture/ddf.py", line 455, in new
    self.set_data_for_a_field(model_class, instance, field, persist_dependencies=persist_dependencies, **configuration)
  File "/home/vagrant/.virtualenvs/env/local/lib/python2.7/site-packages/django_dynamic_fixture/ddf.py", line 372, in set_data_for_a_field
    if django_file.file.mode != 'rb':
AttributeError: '_io.BytesIO' object has no attribute 'mode'
```

And in my tests, Im using 

```
from django.core.files.uploadedfile import SimpleUploadedFile


BASE_FILE = SimpleUploadedFile('test_upload.txt', 'these are the file contents')
G(DjangoFIleModel, file=BASE_FILE)
```

**Comment by paulocheque** [comment]
Thanks for reporting!

Could you give feedback with the new version 1.9.0? I just try to avoid this error, but we can face another kind of issue right now.

**Comment by paulocheque** [comment]
Any news on this @valdergallo ? I will close the issue for now, please re-open if you think it is not solved. ;)
